ppo:
  n_envs: 16
  n_steps: 64
  n_epochs: 4
  batch_size: 256
  learning_rate: 2.5e-4
  lr_schedule: "linear"
  clip_range: 0.2
  gamma: 0.99
  gae_lambda: 0.95
  ent_coef: 0.01
  vf_coef: 0.5
  total_timesteps: 1000000

model:
  device: "cpu"
  feature_dim: 512
