dqn:
  learning_rate: 3.334792728637589e-05
  gamma: 0.99
  batch_size: 8
  replay_buffer_size: 12720
  target_update_freq: 1000
  epsilon_start: 0.6293899908000085
  epsilon_end: 0.13284193458644242
  epsilon_decay_steps: 131216
  learning_starts: 4952
  train_freq: 35
  gradient_steps: 10
  total_timesteps: 500000
model:
  feature_dim: 512
  device: cuda
