dqn:
  learning_rate: 0.0005414413211338525
  gamma: 0.99
  batch_size: 8
  replay_buffer_size: 5725
  target_update_freq: 1000
  epsilon_start: 0.5442462510259598
  epsilon_end: 0.0400005896214099
  epsilon_decay_steps: 83019
  learning_starts: 8949
  train_freq: 598
  gradient_steps: 10
  total_timesteps: 500000
model:
  feature_dim: 512
  device: cuda
